algo = input('Digite Algo :')
print('O tipo primitivo desse valor é {0}'.format(type(algo)))
print('Só tem espaços ? {0}'.format(algo.isspace()))
print('É um número ? {0}'.format(algo.isnumeric()))
print('É alfabético ? {0}'.format(algo.isalpha()))
print('É alfanumérico ? {0}'.format(algo.isalnum()))
print('Está em maiúsculas ? {0}'.format(algo.isupper()))
print('Está em minúsculas ? {0}'.format(algo.islower()))
print('Está captalizado ? {0}'.format(algo.istitle()))
