nome = str(input('Digite seu nome completo :')).strip()
primeiroNome = nome.split()
print('Analisando o seu nome...')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome.replace(' ', ''))))
print('Seu primeiro nome é {} e ele tem {} letras'.format(primeiroNome[0], len(primeiroNome[0])))
